name: CMake Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        operating-system: [macos-latest, windows-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - name: Initialize and update submodules
      run: |
        git submodule update --init --recursive
        cd external/imgui
        git fetch
        git checkout docking
        git pull origin docking

    - name: Install dependencies
      if: matrix.operating-system == 'macos-latest'
      run: |
        brew update
        brew install cmake doxygen sdl2

    - name: Install dependencies
      if: matrix.operating-system == 'windows-latest'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install doxygen
        choco install sdl2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      if: matrix.operating-system == 'macos-latest'
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Test
      if: matrix.operating-system == 'windows-latest'
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Generate Documentation
      if: success()
      working-directory: ${{github.workspace}}/build
      run: cmake --build ${{github.workspace}}/build --target doc_doxygen
