name: Release Build

on:
  push:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Chocolatey and CMake
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Configure Git and Set Upstream
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://github.com/${{ github.repository }}
          git remote -v

      - name: Checkout ImGui docking branch
        if: runner.os == 'Windows'
        run: |
          git -C external/imgui fetch --all
          git -C external/imgui checkout docking || git -C external/imgui checkout -b docking origin/docking
          git -C external/imgui pull origin docking

      - name: Build with CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Prepare Release
        if: success()
        run: |
          mkdir -p release
          cp -r ${{github.workspace}}/build/* release/
          cp -r ${{github.workspace}}/docs/Doxygen release/
          # Add more commands to package other necessary files

      - name: Create Release Directory
        if: success()
        run: mkdir -p release

      - name: Create Tag
        if: success()
        run: git tag -a v${{ github.run_number }} -m "Release version v${{ github.run_number }}"

      - name: Push Tag
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: git push origin v${{ github.run_number }}

      - name: Upload Release Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: peTool-Windows-${{ env.BUILD_TYPE }}
          path: release/
