name: Release Build

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v', e.g., v1.0.0

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Chocolatey and CMake
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Checkout ImGui docking branch
        if: runner.os == 'Windows'
        run: |
          git -C external/imgui fetch --all
          git -C external/imgui checkout docking || git -C external/imgui checkout -b docking origin/docking
          git -C external/imgui pull origin docking

      - name: Build with CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Package Release
        if: success()
        run: |
          mkdir -p release
          cp ${{github.workspace}}/build/peTool.exe release/
          cp -r ${{github.workspace}}/docs/Doxygen release/
          # Add more commands to package other necessary files

      - name: Upload Release Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: peTool-Windows-${{ env.BUILD_TYPE }}
          path: release/
